# Global
website_url: 
jwt_secret: 
github_org_name: www-terminal

# Registry's information
image:
  registry:
    url: registry.gitlab.com/web-terminal
    credentials:
      username: lucj
      password: 

# Authentication service
auth:
  image:
    tag: v1.0.8
  github_client_id:
  github_client_secret: 
  github_callback_url: 
  allowed_origins: 
    
# Websocket server
wss:
  image:
    tag: v1.0.4
  nats_url: "nats://nats:4222"
  vm_user: ubuntu
  allowed_origins: 
  ssh_key: 

# Instance manager
instances:
  image:
    tag: v1.0.1
  exoscale_api_key: 
  exoscale_api_secret:
  database_dsn: "postgres://postgres:postgres@postgres:5432/vmmanager?sslmode=disable"
  nats_url: "nats://nats:4222"

# Web interface (demo as it should be embeded in a website)
www:
  image:
    tag: v1.0.2

nats:
  image:
    repository: nats
    tag: 2.11.2-alpine
  auth:
    enabled: false
  persistence:
    enabled: false

postgres:
  image:
    repository: postgres
    tag: 17.4-alpine3.21
  auth:
    password: postgres
  persistence:
    enabled: false
  database: vmmanager
