apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  {{- if .Values.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.tls.cluster_issuer }}
  {{- end }}
spec:
  rules:
  - host: www.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www
            port:
              number: 80   
  - host: auth.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
  - host: wss.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wss
            port:
              number: 80
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
      - www.{{ .Values.domain }}
      - auth.{{ .Values.domain }}
      - wss.{{ .Values.domain }}
      secretName: terminal-tls
  {{- end }}